Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-12"
  config.vm.box_version = "202502.21.0"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "3"
    vb.memory = "4096"
  end

  config.vm.define "cbourreS" do |server|
    server.vm.network :private_network, ip: "192.168.56.110", interface: "eth1"
    server.vm.hostname = "cbourreS"
  
    server.vm.provision "shell", path: "./scripts/server.sh"
  end
end
