Vagrant.configure("2") do |config|
  # config.vm.box = "debian/bookworm64"
  # config.vm.box_version = "12.20250126.1"
  config.vm.box = "bento/debian-12"
  config.vm.box_version = "202502.21.0"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "1"
    vb.memory = "1024"
  end

  config.vm.define "cbourreS" do |server|
    server.vm.network :private_network, ip: "192.168.56.110"
    server.vm.hostname = "cbourreS"
  
    config.vm.provision "shell", path: "./scriptS.sh"
  end

  config.vm.define "pirabaudSW" do |worker|
    worker.vm.network :private_network, ip: "192.168.56.111"
    worker.vm.hostname = "pirabaudSW"
  
    config.vm.provision "shell", path: "./scriptSW.sh"
  end
end
